pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)   // ✅ changed
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "otpfrauddetection"
include ':app'